name: Rust

on:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'backend/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      working-directory: backend
    - name: Run tests
      run: cargo test --verbose
      working-directory: backend
    - name: Build release
      run: cargo build --release
      working-directory: backend
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: jokkit-backend
        path: backend/target/release/jokkit-backend.exe
